ALTER TABLE daily_reports
    ADD COLUMN IF NOT EXISTS ritase DECIMAL(15,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cuaca VARCHAR(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS catatan TEXT DEFAULT '';
